### ISSUE TITLE
Script AWS resource creation

### ISSUE THREAD

**Issue by BigLep** [protocol/github-mgmt-template#23]
We can simplify the AWS resource creation part of the README (https://github.com/protocol/github-mgmt-template#aws ) by "scripting" it.  This could be a CloudFormation template, CDK, or something else.  I'm not up on the latest/greatest here, but we don't need folks to copy/paste stuff for setting up buckets, tables, and users.  @guseggert or @FunnyGopher may have ideas.

**Comment by galargh** [comment]
You might want to check out the discussion here: https://protocollabs.slack.com/archives/C01LV92B1JB/p1645015508834079

TLDR I used this https://github.com/protocol/ad-hoc-infra/pull/54 to automate AWS bootstrapping - just haven't decided where it's going to live yet. This repo might be a good idea.
