### ISSUE TITLE
Reduce the number of JSONs required to configure GitHub

### ISSUE THREAD

**Issue by galargh** [protocol/github-mgmt-template#36]
For example, we could fold up `team_membership.json` and `team_repository.json` into `team.json`:
```
{
  "TEAM_NAME": {
    "membership": {},
    "repository": {},
    ...
  }
}
```

Or `repository_file.json` into `repository.json`:
```
{
  "REPO_NAME": {
    "file": {},
    ...
  }
}
```

**Comment by galargh** [comment]
Note for self - we could use JSONSchema to describe "our" JSON format.

**Comment by galargh** [comment]
Another useful point of view - https://github.com/libp2p/github-mgmt/issues/6

**Comment by galargh** [comment]
Do this one first - https://github.com/protocol/github-mgmt-template/issues/37 It'll make it easier to complete this task.

**Comment by laurentsenta** [comment]
Closing, @galargh fixed it with https://github.com/protocol/github-mgmt-template/pull/42
