### ISSUE TITLE
Rewrite sync.sh in JS

### ISSUE THREAD

**Issue by galargh** [protocol/github-mgmt-template#37]
It'd make it more accessible to everyone.

**Comment by galargh** [comment]
This setup can be found here: https://github.com/protocol/github-mgmt-template/tree/sync-js

I tested it and it works. I'm not going to merge it on its own though - I'm going to tackle the structure refactor now and merge it together - https://github.com/protocol/github-mgmt-template/issues/36.

**Comment by laurentsenta** [comment]
Closing: @galargh fixed it in https://github.com/protocol/github-mgmt-template/pull/47
